import sqlite3

conn = sqlite3.connect('financial_terms.db')
cursor = conn.cursor()

# cursor.execute("""
# CREATE TABLE IF NOT EXISTS terms (
#     id INTEGER PRIMARY KEY,
#     title TEXT NOT NULL,
#     description TEXT NOT NULL,
#     used BOOLEAN NOT NULL,
#     date_of_using TIMESTAMP
# )
# """)
# conn.commit()


# List of financial terms and their descriptions
financial_terms = [
    ("Yield", "The income generated by an investment, typically expressed as a percentage of the investment's cost or current market value."),
    ("Zero-Coupon Bond", "A debt security that doesn't pay interest but is issued at a discount, providing profit at maturity when the bond is redeemed for its face value."),
    ("Derivative", "A financial contract whose value is based on an underlying asset or group of assets, such as stocks, bonds, or currencies."),
    ("Arbitrage", "The practice of buying and selling an asset simultaneously in different markets to profit from price differences."),
    ("Amortization", "The gradual reduction of a debt by regular scheduled payments of interest and principal, or the write-down of an intangible asset over time."),
    ("Annuity", "A financial product that provides regular payments in exchange for an upfront lump sum, often used as a steady income stream in retirement."),
    ("Beta", "A measure of a stock's volatility in relation to the overall market, with a beta of 1 indicating a stock's price moves with the market."),
    ("Buyout", "The purchase of a controlling interest in a company or a significant portion of its assets, often by private investors or another company."),
    ("Call Option", "A financial contract that gives the buyer the right (but not the obligation) to purchase an asset at a specified price within a set time period."),
    ("Capital Market", "A market for long-term financial assets, such as stocks and bonds, where individuals and institutions can buy and sell securities."),
    ("Commodities", "Basic goods and raw materials, such as gold, oil, or agricultural products, that are traded on exchanges in bulk."),
    ("Common Stock", "A type of stock that represents ownership in a corporation, providing voting rights and a share in the company's profits."),
    ("Coupon Rate", "The annual interest rate paid on a bond, expressed as a percentage of the bond's face value or nominal value."),
    ("Custodian", "A financial institution that holds and safeguards an individual's or entity's financial assets for safekeeping."),
    ("Default", "The failure to repay a loan or meet the obligations of a financial contract, often leading to legal action or loss of collateral."),
    ("Diversification", "The practice of spreading investments across various assets or asset classes to reduce risk and potential losses."),
    ("Dividend Reinvestment Plan (DRIP)", "A plan that allows shareholders to automatically reinvest cash dividends into additional shares of the company."),
    ("Due Diligence", "A comprehensive assessment of a business, investment, or financial deal to confirm facts and evaluate risks before proceeding."),
    ("Equity Financing", "The process of raising capital by selling ownership stakes in a company, typically through issuing shares of stock."),
]
# Inserting the financial terms into the database
for term in financial_terms:
    cursor.execute("""
    INSERT INTO terms (title, description, used, date_of_using) VALUES (?, ?, ?, ?)
    """, (*term, False, None))
conn.commit()

# Verifying the data insertion by retrieving the first 10 records
cursor.execute("SELECT title, description FROM terms LIMIT 10")
first_10_terms = cursor.fetchall()
first_10_terms